steps:
  - label: ":julia: Julia {{matrix.julia}} + CUDA GPU"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.julia}}"
      - JuliaCI/julia-test#v1:
          test_args: "--quickfail"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - ext
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      GROUP: "CUDA"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 240
    matrix:
      setup:
        julia:
          - "1"

  - label: ":open_book: Documentation"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-coverage#v1:
          codecov: true
          dirs:
            - src
            - ext
    command: |
      julia --project --code-coverage=user --color=yes --threads=3 -e '
        println("--- :julia: Instantiating project")
        using Pkg
        Pkg.instantiate()
        Pkg.activate("docs")
        Pkg.develop(PackageSpec(path=pwd()))
        Pkg.instantiate()
        println("+++ :julia: Building documentation")

        Pkg.activate("docs")
        include("docs/make.jl")'
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      DATADEPS_ALWAYS_ACCEPT: true
      JULIA_DEBUG: "Documenter"
      GKSwstype: "100" # https://discourse.julialang.org/t/generation-of-documentation-fails-qt-qpa-xcb-could-not-connect-to-display/60988
    if: build.message !~ /\[skip docs\]/
    timeout_in_minutes: 240

env:
  SECRET_CODECOV_TOKEN: "fbSN+ZbScLIWr1FOpAu1Z8PYWFobqbLGFayOgZE1ebhE8LIH/PILGXUMcdm9gkXVSwgdETDD0s33k14lBkJ90O4dV9w6k79F/pEgzVHV8baMoXZG03BPMxztlcoRXrKtRtAp+MwoATc3Ldb9H5vqgAnVNn5rhn4Rp0Z6LOVRC43hbhKBBKYh/N4gqpIQlcW4dBXmELhlnMFnUILjwGRVgEt/zh8H+vmf0qiIulNIQ/rfGISROHqFML0QDL4icloiqX08J76ZP/gZCeg6rJ0gl3ok3IspNPz51rlbvijqsPNyIHWi29OrAtWX3qKHfrAOoGIrE1d5Oy4wx4XaN/YBhg==;U2FsdGVkX188gcRjkUNMEC2Z5fEFfhsYY4WJbhhINOuCUgqq9XNHVDbJhzFUFVQ+UiuPHFg7CW/gn+3IkSVyOA=="
  SECRET_DOCUMENTER_KEY: "nIiMZCYpVq7ZJVZiSxS/xj1bqHWro1+5b2iq1cQluCDYEdWQc1QQu/PxfXUEaYYCj+1ZRQZabXv8Zqz2zdACeBT3btVgVf3EnWENJOK0BnP0XYpK/q1ARP1skexBIq3xokggvOcgf7n6JO3uuIwIQfbZK4oV7Cam92tJHmplUhbJdtAa63DlwzRgw4Ti5Brydl1QcIK4oX9PJmg1T/nybGFGD+IOtvaqUtxUJ9mlQhzfwITqFEyLI6ZpzAgzjQ84akiaz4ClHbpJSOZHR3ljSYkbrDiQA0Z2Cj9MZ84ApfNdA8SFIp66hnhkBEleX4g2bOFBX7FcZDT898roq1en9Q==;U2FsdGVkX18nuQu5WxxuFt5wZ2qgOXw7V2emSyef/iWOJYWHZA+vPceeUYoV8E2JCDbCdWoYJWylk9SUA8OvtibGv5D1lpUgKlGlc8YNWjDh3qDdNb04tFvmmmGvN/bAbMOtDaOuzH8wlduofdtC/OhV+TP6pmn2vMiaRM6xqrLhbZOjN77Cjb4KOLImwt2ejotu3WhKE2KJ2uwC24/rtfx9nQlh8HLSkJBZDM3+eQQTdJrmwJRXmXovm3Lvv4faDoRyc7sNHsS37MTUUwjAFSw8OunU27ia1/Y3CL7UC/oyvf8HnCWDBNL6wDUlImzUz2JZH0vyxvzT6X3IKL1roAPG9jZHk6AZ0rY5o3PfWkhMO2NuQE0AeCXUsIK6sNB8T1C+77EZjhu6hJSWqfaVdjKrmxL9xdCgIjQhcel1fh/svwTO5miB7RPhZxHBbSloSGt5siRSI31W/wOKhZKOIfA8EuRY1yNSf5nchbCS7gSCSXSfZ6eixsZr+gAgs7h+Pg5yARwMLV34sgvDwtKem6UZgOVzUc4WVp3IF5vP/aF4sI/bP5Yq1cTam42mjc3OJDSlQSebHygo+Aw24ovWsYccXQ+Q3Jt1j4rC+DuKRjTuU9NJYSZLRWh86QW0TAmdg4Ev5r6sOGD3vNqLZe9hxAOX6zIGaur8dIcruJHIDLDKdI9wVgFnM/hlFtuPnSvy961SvxAtIDxZUdS8Hhb083dwLK/j9UI/K47y6grkGq9451cmeRnCEfa3I+NQKkWOy6V0HAYymgA0MIS1Eca/1Q=="
